name: cml-wd-telcosense

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python>=3.19,<3.13
  - pip
  - numpy>=1.26,<3.0
  - scipy>=1.12,<2.0
  - scikit-learn>=1.4,<2.0
  - pytorch>=2.3,<3.0
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - tqdm
  - pycomlink